### ISSUE TITLE
Provision new ECS cluster

### ISSUE THREAD

**Issue by sukrit007** [totem/totem-v3#1]
As a **developer**, I need the ability to create and destroy a new ECS cluster so that I can deploy my application to this cluster.

**Acceptance Criteria**
- Automated process for creating and destroying ECS cluster with minimal steps.
- Ability to execute the provisioning in a repeatable manner.
- Documentation, including diagram, of newly provisioned infrastructure.

**Notes:**
- Architectural components and steps should be documented

**Comment by mmoulton** [comment]
If you want @sukrit007, it would be reasonable to move `Ability to deploy a sample application to this cluster.` to it's own story. That would cut down the effort to be done with this particular story.

**Comment by sukrit007** [comment]
@mmoulton  probably we can rename sample application to an "ECS Task or Service" to validate the cluster.  Thoughts ?

**Comment by sukrit007** [comment]
Based on offline discussions with @mmoulton , we decide we do not need to validate the cluster as part of this step.  Updating A.C. to remove that point.

**Comment by sukrit007** [comment]
Issue is fixed and approved by @mmoulton
